import React, { useState } from 'react';
import { 
  Layers, 
  Sparkles, 
  Loader2, 
  RotateCw, 
  ChevronLeft, 
  ChevronRight, 
  Check, 
  X, 
  HelpCircle,
  Brain
} from 'lucide-react';
import { generateFlashcards, askAITutor } from '../services/gemini';

export default function FlashcardsView({ material }) {
  const [deck, setDeck] = useState(null);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState(null);

  // AI clarification state
  const [aiExplanation, setAiExplanation] = useState(null);
  const [isExplaining, setIsExplaining] = useState(false);

  // Self-rating counts
  const [masteredIds, setMasteredIds] = useState(new Set());
  const [reviewIds, setReviewIds] = useState(new Set());

  const handleGenerateDeck = async () => {
    if (!material?.content) return;
    setIsLoading(true);
    setError(null);
    try {
      const generated = await generateFlashcards({
        materialContent: material.content,
        count: 8
      });
      setDeck(generated);
      setCurrentIndex(0);
      setIsFlipped(false);
      setMasteredIds(new Set());
      setReviewIds(new Set());
      setAiExplanation(null);
    } catch (err) {
      setError(`Failed to generate flashcards: ${err.message}`);
    } finally {
      setIsLoading(false);
    }
  };

  const handleFlip = () => {
    setIsFlipped(prev => !prev);
  };

  const handleNext = () => {
    if (!deck) return;
    setIsFlipped(false);
    setAiExplanation(null);
    setCurrentIndex(prev => (prev + 1) % deck.cards.length);
  };

  const handlePrev = () => {
    if (!deck) return;
    setIsFlipped(false);
    setAiExplanation(null);
    setCurrentIndex(prev => (prev - 1 + deck.cards.length) % deck.cards.length);
  };

  const handleMarkMastered = () => {
    if (!deck) return;
    const currentCard = deck.cards[currentIndex];
    setMasteredIds(prev => new Set([...prev, currentCard.id]));
    setReviewIds(prev => {
      const next = new Set(prev);
      next.delete(currentCard.id);
      return next;
    });
    handleNext();
  };

  const handleMarkReview = () => {
    if (!deck) return;
    const currentCard = deck.cards[currentIndex];
    setReviewIds(prev => new Set([...prev, currentCard.id]));
    setMasteredIds(prev => {
      const next = new Set(prev);
      next.delete(currentCard.id);
      return next;
    });
    handleNext();
  };

  const handleAskAIClarification = async () => {
    if (!deck) return;
    const currentCard = deck.cards[currentIndex];
    setIsExplaining(true);
    try {
      const exp = await askAITutor({
        materialContent: material.content,
        question: `Explain this flashcard concept in more detail: "${currentCard.front}" - Answer: "${currentCard.back}"`,
        persona: 'feynman'
      });
      setAiExplanation(exp);
    } catch (e) {
      setAiExplanation(`Clarification error: ${e.message}`);
    } finally {
      setIsExplaining(false);
    }
  };

  return (
    <div className="tab-viewport">
      {/* Header Banner */}
      <div className="glass-card" style={{
        padding: '1.25rem 1.5rem',
        marginBottom: '1.5rem',
        display: 'flex',
        alignItems: 'center',
        justify-content: 'space-between',
        flexWrap: 'wrap',
        gap: '1rem'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.8rem' }}>
          <div style={{
            width: '40px',
            height: '40px',
            borderRadius: '12px',
            background: 'var(--accent-purple)',
            display: 'flex',
            alignItems: 'center',
            justify-content: 'center',
            color: '#fff',
            boxShadow: '0 4px 12px rgba(139, 92, 246, 0.4)'
          }}>
            <Layers size={22} />
          </div>
          <div>
            <h2 style={{ fontSize: '1.15rem', fontWeight: 800 }}>AI Interactive Flashcards</h2>
            <p style={{ fontSize: '0.825rem', color: 'var(--text-secondary)' }}>
              Spaced repetition active recall deck dynamically generated by Gemini.
            </p>
          </div>
        </div>

        <button
          className="btn-primary"
          onClick={handleGenerateDeck}
          disabled={isLoading}
        >
          {isLoading ? (
            <>
              <Loader2 size={18} className="spinner" />
              <span>Generating Deck...</span>
            </>
          ) : (
            <>
              <Sparkles size={18} />
              <span>{deck ? 'Regenerate Flashcards' : 'Generate Flashcards'}</span>
            </>
          )}
        </button>
      </div>

      {error && (
        <div style={{
          background: 'rgba(244, 63, 94, 0.15)',
          border: '1px solid rgba(244, 63, 94, 0.3)',
          color: 'var(--accent-rose)',
          padding: '1rem',
          borderRadius: 'var(--radius-lg)',
          marginBottom: '1.5rem',
          fontSize: '0.9rem'
        }}>
          {error}
        </div>
      )}

      {/* Empty State */}
      {!deck && !isLoading && !error && (
        <div className="glass-card" style={{ padding: '3rem 1.5rem', textAlign: 'center', maxWidth: '500px', margin: '2rem auto' }}>
          <Layers size={48} style={{ color: 'var(--accent-purple)', marginBottom: '1rem', opacity: 0.8 }} />
          <h3 style={{ fontSize: '1.2rem', fontWeight: 700 }}>No Active Flashcard Deck</h3>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.875rem', marginTop: '0.5rem', marginBottom: '1.5rem' }}>
            Click below to let Gemini extract high-yield concept cards from your material.
          </p>
          <button className="btn-primary" onClick={handleGenerateDeck}>
            <Sparkles size={18} />
            <span>Generate Flashcard Deck</span>
          </button>
        </div>
      )}

      {/* Active Deck View */}
      {deck && !isLoading && (
        <div style={{ maxWidth: '640px', margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          {/* Deck Stats Bar */}
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', fontSize: '0.85rem' }}>
            <span style={{ color: 'var(--text-secondary)' }}>
              Card {currentIndex + 1} of {deck.cards.length}
            </span>
            <div style={{ display: 'flex', gap: '1rem' }}>
              <span style={{ color: 'var(--accent-emerald)', fontWeight: 600 }}>Mastered: {masteredIds.size}</span>
              <span style={{ color: 'var(--accent-rose)', fontWeight: 600 }}>Needs Review: {reviewIds.size}</span>
            </div>
          </div>

          {/* 3D Flip Card Container */}
          {(() => {
            const card = deck.cards[currentIndex];
            if (!card) return null;

            return (
              <div 
                onClick={handleFlip}
                style={{
                  height: '320px',
                  perspective: '1000px',
                  cursor: 'pointer',
                  userSelect: 'none'
                }}
              >
                <div style={{
                  position: 'relative',
                  width: '100%',
                  height: '100%',
                  transition: 'transform 0.6s cubic-bezier(0.4, 0, 0.2, 1)',
                  transformStyle: 'preserve-3d',
                  transform: isFlipped ? 'rotateY(180deg)' : 'rotateY(0deg)'
                }}>
                  {/* FRONT SIDE */}
                  <div className="glass-card" style={{
                    position: 'absolute',
                    inset: 0,
                    backfaceVisibility: 'hidden',
                    display: 'flex',
                    flexDirection: 'column',
                    justify-content: 'space-between',
                    padding: '2rem',
                    background: 'linear-gradient(135deg, var(--bg-card) 0%, var(--bg-tertiary) 100%)',
                    border: '1px solid var(--border-medium)',
                    boxShadow: 'var(--shadow-lg)'
                  }}>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                      <span style={{ fontSize: '0.75rem', fontWeight: 700, textTransform: 'uppercase', color: 'var(--accent-purple)' }}>
                        {card.category || 'Concept'}
                      </span>
                      <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '0.3rem' }}>
                        <RotateCw size={13} /> Click to Flip
                      </span>
                    </div>

                    <div style={{ fontSize: '1.25rem', fontWeight: 700, textAlign: 'center', lineHeight: 1.5, color: 'var(--text-primary)' }}>
                      {card.front}
                    </div>

                    <div style={{ fontSize: '0.8rem', color: 'var(--text-muted)', textAlign: 'center' }}>
                      💡 Hint: {card.hint || 'Think about core principles'}
                    </div>
                  </div>

                  {/* BACK SIDE */}
                  <div className="glass-card" style={{
                    position: 'absolute',
                    inset: 0,
                    backfaceVisibility: 'hidden',
                    transform: 'rotateY(180deg)',
                    display: 'flex',
                    flexDirection: 'column',
                    justify-content: 'space-between',
                    padding: '2rem',
                    background: 'linear-gradient(135deg, rgba(139, 92, 246, 0.15) 0%, var(--bg-card) 100%)',
                    border: '1px solid var(--accent-purple)',
                    boxShadow: 'var(--shadow-glow)'
                  }}>
                    <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                      <span style={{ fontSize: '0.75rem', fontWeight: 700, color: 'var(--accent-purple)' }}>
                        Answer / Explanation
                      </span>
                      <span style={{ fontSize: '0.75rem', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', gap: '0.3rem' }}>
                        <RotateCw size={13} /> Click to Flip
                      </span>
                    </div>

                    <div style={{ fontSize: '1.05rem', fontWeight: 500, lineHeight: 1.6, color: 'var(--text-primary)', textAlign: 'center' }}>
                      {card.back}
                    </div>

                    <div style={{ display: 'flex', justifyContent: 'center' }}>
                      <button
                        className="btn-ghost"
                        onClick={(e) => {
                          e.stopPropagation();
                          handleAskAIClarification();
                        }}
                        disabled={isExplaining}
                        style={{ fontSize: '0.775rem', gap: '0.4rem', color: 'var(--accent-secondary)' }}
                      >
                        {isExplaining ? <Loader2 size={14} className="spinner" /> : <Brain size={14} />}
                        <span>Ask AI to Clarify Card</span>
                      </button>
                    </div>
                  </div>
                </div>
              </div>
            );
          })()}

          {/* AI Explanation Callout if requested */}
          {aiExplanation && (
            <div className="glass-card" style={{ borderLeft: '4px solid var(--accent-secondary)', fontSize: '0.85rem', lineHeight: 1.6 }}>
              <div style={{ fontWeight: 700, color: 'var(--accent-secondary)', marginBottom: '0.35rem' }}>
                🧠 Gemini AI Clarification:
              </div>
              <div style={{ whiteSpace: 'pre-wrap' }}>{aiExplanation}</div>
            </div>
          )}

          {/* Card Grading & Navigation Controls */}
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: '1rem' }}>
            <button className="btn-secondary" onClick={handlePrev} style={{ padding: '0.6rem 0.9rem' }}>
              <ChevronLeft size={18} />
            </button>

            <div style={{ display: 'flex', gap: '0.75rem', flex: 1 }}>
              <button 
                className="btn-secondary" 
                onClick={handleMarkReview}
                style={{ flex: 1, justifyContent: 'center', borderColor: 'var(--accent-rose)', color: 'var(--accent-rose)' }}
              >
                <X size={16} />
                <span>Hard / Review</span>
              </button>

              <button 
                className="btn-primary" 
                onClick={handleMarkMastered}
                style={{ flex: 1, justifyContent: 'center', background: 'var(--accent-emerald)' }}
              >
                <Check size={16} />
                <span>Got It! (Mastered)</span>
              </button>
            </div>

            <button className="btn-secondary" onClick={handleNext} style={{ padding: '0.6rem 0.9rem' }}>
              <ChevronRight size={18} />
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
